/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerImp;
import Model.HoSo;
import Model.TinTuyenDung;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang
 */
public class TrangChuView extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuView
     */
    private final String fileTinTD = "TinTuyenDung.txt";
    private final String fileHoSo = "HoSo.txt";
    private ControllerImp controller;
    private List<TinTuyenDung> listTinTD;
    private DefaultTableModel modelTinTD;
    private List<HoSo> listHoSo;
    private DefaultTableModel modelHoSo;
    private int indexTinTDSelected;

    public TrangChuView() {
        initComponents();
        setLocationRelativeTo(null);
        controller = new ControllerImp();
        listTinTD = new ArrayList<>();
        modelTinTD = (DefaultTableModel) tblTinTD.getModel();

        docFileTinTuyenDung();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TrangChu = new javax.swing.JPanel();
        btnDangXuat1 = new javax.swing.JButton();
        labelDSTinTD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTinTD = new javax.swing.JTable();
        btnThemTin = new javax.swing.JButton();
        btnSuaTin = new javax.swing.JButton();
        btnXoaTin = new javax.swing.JButton();
        labelTongViTriTD = new javax.swing.JLabel();
        labelTongSoLuongTD = new javax.swing.JLabel();
        txtTongSoTin = new javax.swing.JTextField();
        txtTongSLTuyen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDangXuat2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoSo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTongHoSo = new javax.swing.JTextField();
        btnThemHS = new javax.swing.JButton();
        btnSuaHS = new javax.swing.JButton();
        btnXoaHS = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân sự Trường Đại học Công Nghiệp Hà Nội");

        btnDangXuat1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDangXuat1.setText("Đăng xuất");
        btnDangXuat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuat1ActionPerformed(evt);
            }
        });

        labelDSTinTD.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        labelDSTinTD.setText("Danh sách tin tuyển dụng");

        tblTinTD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTinTD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tin", "Vị trí tuyển dụng", "Yêu cầu dự tuyển", "Số lượng", "Hạn nộp hồ sơ"
            }
        ));
        tblTinTD.setDoubleBuffered(true);
        tblTinTD.setName(""); // NOI18N
        tblTinTD.setRowHeight(25);
        tblTinTD.setShowGrid(false);
        jScrollPane1.setViewportView(tblTinTD);

        btnThemTin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemTin.setText("Thêm tin");
        btnThemTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTinActionPerformed(evt);
            }
        });

        btnSuaTin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaTin.setText("Sửa tin");
        btnSuaTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTinActionPerformed(evt);
            }
        });

        btnXoaTin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaTin.setText("Xoá tin");
        btnXoaTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTinActionPerformed(evt);
            }
        });

        labelTongViTriTD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTongViTriTD.setText("Tổng số tin tuyển dụng:");

        labelTongSoLuongTD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTongSoLuongTD.setText("Tổng số lượng tuyển dụng:");

        txtTongSoTin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTongSLTuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrangChuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDSTinTD)
                        .addGap(172, 172, 172)
                        .addComponent(btnDangXuat1))
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelTongViTriTD)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongSoTin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTongSoLuongTD)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongSLTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnThemTin)
                        .addGap(174, 174, 174)
                        .addComponent(btnSuaTin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaTin)
                        .addGap(127, 127, 127)))
                .addContainerGap())
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDangXuat1))
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelDSTinTD)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTongViTriTD)
                    .addComponent(txtTongSoTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTongSoLuongTD)
                    .addComponent(txtTongSLTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTin)
                    .addComponent(btnSuaTin)
                    .addComponent(btnXoaTin))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QL Tin tuyển dụng", TrangChu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Danh sách hồ sơ");

        btnDangXuat2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDangXuat2.setText("Đăng xuất");

        tblHoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblHoSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Giới tính", "Năm sinh", "Địa chỉ", "Trình độ", "Vị trí tuyển dụng", "Trạng thái"
            }
        ));
        jScrollPane3.setViewportView(tblHoSo);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tổng số hồ sơ:");

        txtTongHoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnThemHS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemHS.setText("Thêm hồ sơ");

        btnSuaHS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaHS.setText("Sửa hồ sơ");

        btnXoaHS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaHS.setText("Xoá hồ sơ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(240, 240, 240)
                        .addComponent(btnDangXuat2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnThemHS)
                        .addGap(148, 148, 148)
                        .addComponent(btnSuaHS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaHS)
                        .addGap(129, 129, 129)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangXuat2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTongHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHS)
                    .addComponent(btnSuaHS)
                    .addComponent(btnXoaHS))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("QL Hồ Sơ", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("QL Khoa - Phòng ban", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("QL Nhân sự", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuat1ActionPerformed
        DangNhapView dangNhap = new DangNhapView();
        dangNhap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuat1ActionPerformed

    private void btnThemTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTinActionPerformed
        ThemTinForm themTinForm = new ThemTinForm(this, rootPaneCheckingEnabled);
        themTinForm.pack();
        themTinForm.setVisible(true);
    }//GEN-LAST:event_btnThemTinActionPerformed

    private void btnSuaTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTinActionPerformed
        if (listTinTD.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Danh sách tin trống!");
        } else {
            indexTinTDSelected = tblTinTD.getSelectedRow();
            if (indexTinTDSelected < 0) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn tin cần sửa!");
            } else {
                SuaTinForm suaTinForm = new SuaTinForm(this, rootPaneCheckingEnabled);
                suaTinForm.setEditData(listTinTD.get(indexTinTDSelected));
                suaTinForm.pack();
                suaTinForm.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSuaTinActionPerformed

    private void btnXoaTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTinActionPerformed
        if (listTinTD.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Danh sách tin trống!");
        } else {
            indexTinTDSelected = tblTinTD.getSelectedRow();
            if (indexTinTDSelected < 0) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn tin cần xoá!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xoá bản ghi này?");
                if (luaChon == JOptionPane.YES_OPTION) {
                    listTinTD.remove(indexTinTDSelected);
                    controller.ghiFile(listTinTD, fileTinTD);
                    showDataTinTuyenDung();
                }
            }
        }
    }//GEN-LAST:event_btnXoaTinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TrangChu;
    private javax.swing.JButton btnDangXuat1;
    private javax.swing.JButton btnDangXuat2;
    private javax.swing.JButton btnSuaHS;
    private javax.swing.JButton btnSuaTin;
    private javax.swing.JButton btnThemHS;
    private javax.swing.JButton btnThemTin;
    private javax.swing.JButton btnXoaHS;
    private javax.swing.JButton btnXoaTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDSTinTD;
    private javax.swing.JLabel labelTongSoLuongTD;
    private javax.swing.JLabel labelTongViTriTD;
    private javax.swing.JTable tblHoSo;
    private javax.swing.JTable tblTinTD;
    private javax.swing.JTextField txtTongHoSo;
    private javax.swing.JTextField txtTongSLTuyen;
    private javax.swing.JTextField txtTongSoTin;
    // End of variables declaration//GEN-END:variables

    // Hiển thị danh sách tin tin tuyển dụng
    public void showDataTinTuyenDung() {
        modelTinTD.setRowCount(0);
        int tongSoTin = listTinTD.size(), tongSLTuyen = 0;
        for (TinTuyenDung tin : listTinTD) {
            modelTinTD.addRow(new Object[]{
                tin.getMaTin(), tin.getViTri(), tin.getYeuCau(), tin.getSoLuong(), tin.getHanNopHoSo()
            });
            tongSLTuyen += tin.getSoLuong();
        }
        txtTongSoTin.setText(tongSoTin + "");
        txtTongSLTuyen.setText(tongSLTuyen + "");
    }

    // Đọc dữ liệu file tin tuyển dụng
    private void docFileTinTuyenDung() {
        listTinTD = controller.docFile(fileTinTD);
        if (listTinTD.size() > 0) {
            int id = listTinTD.get(listTinTD.size() - 1).getMaTin();
            TinTuyenDung.setId(id + 1);
        }
        showDataTinTuyenDung();
    }

    // Thêm tin tuyển dụng
    public void themTinTD(TinTuyenDung tin) {
        listTinTD.add(tin);
        this.showDataTinTuyenDung();
        controller.ghiFile(listTinTD, fileTinTD);
    }

    // Sửa tin tuyển dụng
    public void suaTinTD(TinTuyenDung tin) {
        listTinTD.set(indexTinTDSelected, tin);
        this.showDataTinTuyenDung();
        controller.ghiFile(listTinTD, fileTinTD);
    }
}
