/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.HoSo;
import Model.NhanSu;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class SuaNhanSuForm extends javax.swing.JDialog {

    /**
     * Creates new form SuaNhanSuForm
     */
    
    private TrangChuView trangChu;
    private NhanSu nhanSuCanSua;
    private String trinhDoCanSua;
    
    public SuaNhanSuForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        trangChu = (TrangChuView) parent;
        this.setLocationRelativeTo(null);
        this.setTitle("Sửa thông tin nhân sự");
        txtMaNS.setEnabled(false);
        txtMaHS.setEnabled(false);
        labelErrorHoTen.setVisible(false);
        labelErrorDiaChi.setVisible(false);
        labelErrorSDT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNS = new javax.swing.JTextField();
        txtMaHS = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        cboTrinhDo = new javax.swing.JComboBox<>();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        labelErrorHoTen = new javax.swing.JLabel();
        labelErrorDiaChi = new javax.swing.JLabel();
        labelErrorSDT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa nhân sự");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sửa thông tin nhân sự");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mã nhân sự:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã hồ sơ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Họ tên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("SĐT:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Trình độ:");

        txtMaNS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaNS.setEnabled(false);

        txtMaHS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaHS.setEnabled(false);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cboTrinhDo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboTrinhDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cao đẳng", "Đại học", "Thạc sĩ", "Tiến sĩ" }));
        cboTrinhDo.setSelectedIndex(1);

        btnCapNhat.setBackground(new java.awt.Color(102, 204, 0));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(153, 153, 153));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        labelErrorHoTen.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorHoTen.setText("Họ tên chỉ được chứa chữ cái!");

        labelErrorDiaChi.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorDiaChi.setText("Địa chỉ không được trống!");

        labelErrorSDT.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorSDT.setText("SĐT không hợp lệ! (phải đủ 10 số, VD: 0123456789)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnCapNhat)
                .addGap(68, 68, 68)
                .addComponent(btnLamMoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelErrorHoTen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTrinhDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSDT)
                            .addComponent(txtDiaChi)
                            .addComponent(txtMaNS)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaHS, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErrorSDT)
                            .addComponent(labelErrorDiaChi))
                        .addGap(0, 77, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelErrorHoTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(labelErrorDiaChi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(labelErrorSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnLamMoi))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        boolean isOk = true;

        String hoTen = txtHoTen.getText().trim();
        if (hoTen.isEmpty()) {
            labelErrorHoTen.setVisible(true);
            isOk = false;
        } else {
            if (!hoTen.matches("^[a-zA-Z\\sÀ-ỹ]+$")) {
                labelErrorHoTen.setVisible(true);
                isOk = false;
            } else {
                labelErrorHoTen.setVisible(false);
            }
        }
        
        String diaChi = txtDiaChi.getText().trim();
        if (diaChi.isEmpty()) {
            labelErrorDiaChi.setVisible(true);
            isOk = false;
        } else {
            labelErrorDiaChi.setVisible(false);
        }
        
        String sdt = txtSDT.getText().trim();
        if (sdt.isEmpty() || !sdt.matches("^0\\d{9}$")) {
            labelErrorSDT.setVisible(true);
            isOk = false;
        } else {
            labelErrorSDT.setVisible(false);
        }
        
        String trinhDo = cboTrinhDo.getSelectedItem().toString().trim();
        
        if (isOk) {
            HoSo h = new HoSo(hoTen, diaChi, sdt, trinhDo);
            NhanSu ns = new NhanSu(h);
            ns.setMaNhanSu(Integer.parseInt(txtMaNS.getText()));
            ns.getHoSo().setMaHoSo(Integer.parseInt(txtMaHS.getText()));
            trangChu.suaNhanSu(ns);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công!",
                "Thông báo sửa thành công", JOptionPane.INFORMATION_MESSAGE);
            trangChu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtHoTen.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        cboTrinhDo.setSelectedItem(trinhDoCanSua);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhanSuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhanSuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhanSuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhanSuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaNhanSuForm dialog = new SuaNhanSuForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    void setEditData(NhanSu ns) {
        nhanSuCanSua = ns;
        trinhDoCanSua = ns.getTrinhDo().trim();
        txtMaNS.setText(ns.getMaNhanSu() + "");
        txtMaHS.setText(ns.getHoSo().getMaHoSo() + "");
        txtHoTen.setText(ns.getHoSo().getHoTen());
        txtDiaChi.setText(ns.getHoSo().getDiaChi());
        txtSDT.setText(ns.getHoSo().getSdt());
        cboTrinhDo.setSelectedItem(ns.getHoSo().getTrinhDo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JComboBox<String> cboTrinhDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelErrorDiaChi;
    private javax.swing.JLabel labelErrorHoTen;
    private javax.swing.JLabel labelErrorSDT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaHS;
    private javax.swing.JTextField txtMaNS;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
